steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${qyou-r}/qrcodeapp:latest'
    - '.' # Build context is the current directory
  env:
    - 'DOCKER_BUILDKIT=1' # <-- THIS IS THE KEY LINE
images:
  - 'gcr.io/${qyou-r}/qrcodeapp:latest'