steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - DOCKER_BUILDKIT=1 docker build -t gcr.io/qyou-r/qrcodeapp:latest .
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/qyou-r/qrcodeapp:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'qrcodeapp'
      - '--image=gcr.io/qyou-r/qrcodeapp:latest'
      - '--region=me-west1' # Change region if needed
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000' # Specify the port your application listens on      
    env:
      - 'PORT=8000' # Set the PORT environment variable for the app

images:
  - 'gcr.io/qyou-r/qrcodeapp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
